# Site settings
title: GEC's GitHub Pages
author:
  name: gechong
  email: jngechong@gmail.com
description: "My personal GitHub Pages for my blogs."

# Build settings
# remote_theme: jekyll/minima
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
